eureka:
  instance:
    hostname:localhost
  client:
    register-with-eureka: false //service should not become a microservice bydefault true
    fetch-registry:false // cant register to itself , bydefault true
server:
  port:8761