server:
	port:8082

spring:
	datasource:
		url:postgresql://localhost:5432/mircoservice
	   	username:root
		password:postgres
	jpa:
	   hibernate:
		ddl-auto:update
	   show-sql:true
		
	application:
		name:HOTEL-Service

	
	eureka:
		instance:
			prefer-ip-address:true
		client:
			fetch-registry:true
			register-with-eureka:true
			service-url:
				defaultZone:http://localhost:8761/eureka
